// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvnwcxfnazwqpfasuztv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2bndjeGZuYXp3cXBmYXN1enR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExNzE4OTcsImV4cCI6MjA3Njc0Nzg5N30.GnojnE5NgRBH9kvE9Ddkj7gel3YbyXvDtnYxUruFxaM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    // Injeta Authorization em cada requisição REST/Functions
    fetch: (input, init = {}) => {
      const token = localStorage.getItem('session_token');
      const headers = new Headers((init as RequestInit)?.headers || {});
      if (token) headers.set('x-session-token', token);
      return fetch(input as RequestInfo, { ...init, headers });
    },
  },
});